version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Compress source
                command: tar -zcvf bloodhound.tar.gz node_modules/ *.js
            - add_ssh_keys:
                fingerprints:
                  - "76:ce:2e:90:ed:8b:8d:1e:e3:c0:47:b7:09:5e:af:ef"
            - run:
                name: Upload to EC2
                command: |
                  echo $EC2_HOST >> ~/.ssh/known_hosts
                  scp bloodhound.tar.gz ${EC2_USER}@${EC2_ADDRESS}:/home/$EC2_USER
                  ssh ${EC2_USER}@${EC2_ADDRESS}
                  tar -xvzf bloodhound.tar.gz
                  exit

workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy