version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Compress source
                command: tar -zcvf bloodhound.tar.gz node_modules/ setup.sh *.js
            - add_ssh_keys:
                fingerprints:
                  - "76:ce:2e:90:ed:8b:8d:1e:e3:c0:47:b7:09:5e:af:ef"
            - run:
                name: Upload to EC2
                command: |
                  echo $EC2_HOST >> ~/.ssh/known_hosts
                  ssh ec2-user@${EC2_ADDRESS} rm -rf bloodhound/*
                  scp bloodhound.tar.gz ec2-user@${EC2_ADDRESS}:/home/ec2-user/bloodhound
                  ssh ec2-user@${EC2_ADDRESS} "cd bloodhound && tar -xvzf bloodhound.tar.gz && pwd && ls -a && ./setup.sh && exit"

workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy