version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Compress source
                command: tar -zcvf bloodhound.tar.gz node_modules/ *.js
            - run:
                name: Upload to EC2
                command: |
                  scp bloodhound.tar.gz $EC2_USER:$EC2_WORKSPACE
                  ssh $EC2_USER
                  tar -xvzf bloodhound.tar.gz
                  exit

workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy